; Project Reality: BF2 - Saitek X52 Pro configuration.
; PR:BF2 v1.0 comes with support for controlling the X52 Pro's MFD and LED's while flying air vehicles.
; Some default settings have been provided, however it's likely you will need to configure these depending on your personal preference and button mapping.

[Settings]
; Defines whether or not you want Project Reality: BF2 to control the X52 Pro lights. This will also stop the LED's from flashing on events.
; 1 = enable, 0 = disable
EnableLights = 1

; Defines whether or not you want Project Reality: BF2 to add a page to the MFD on the throttle to display coordinate information.
; 1 = enable, 0 = disable
EnableMFD = 1

; Defines whether or not you want Project Reality: BF2 to automatically load and unload the "Project_Reality.pr0" profile when the game is running.
; 1 = enable, 0 = disable
EnableProfile = 1

[LED]
; Defines which LED's turn on when you hop in an air vehicle
; 1 = on, 0 = off

FireIllumination = 1
FireARed = 1
FireAGreen = 1
FireBRed = 0
FireBGreen = 1
FireDRed = 1
FireDGreen = 1
FireERed = 0
FireEGreen = 1
Toggle12Red = 1
Toggle12Green = 0
Toggle34Red = 0
Toggle34Green = 1
Toggle56Red = 1
Toggle56Green = 1
Pov2Red = 1
Pov2Green = 1
ClutchRed = 1
ClutchGreen = 0
ThrottleIllumination = 1

[Events]
; Defines which buttons flash when the event occurs
; Use the values from the [LED] section above for the values.
; Use comma delimited values for setting multiple LED's to flash (ie, FireARed,FireAGreen)
; An invalid button or empty value (ie, nothing after = ) will result in no button flashing for that event

; GotLock occurs when you lock onto a target (so you should set to your secondary fire button)
GotLock = FireIllumination

; The buttons LED's you want to disable when the GotLock event has fired
GotLockDisable =

; Flares occurs when you receive a lock and you should launch counter-measures (so you should set to your flares button)
ReceiveLock = FireDRed

; The buttons LED's you want to turn off when the ReceiveLock event has fired
ReceiveLockDisable = FireDGreen